default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: stock-data-portfolio   # ご主人様のGCPプロジェクトID
      dataset: us_stock               # dbtで使うデータセット
      keyfile: key.json               # Actions内で作られる一時ファイル
      threads: 4
      timeout_seconds: 300
      priority: interactive
